import type { Metadata } from "next";
import "./globals.css";
import "./react-time-picker-global.css";
import AuthProvider from "@/components/AuthProvider";

export const metadata: Metadata = {
  title: "AirbnbL&J",
  description: "Generated by Readdy",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" suppressHydrationWarning={true}>
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
