// lib/amenitiesList.ts
export const AMENITIES = [
  { label: "바비큐장", value: "barbecue" },
  { label: "뷰티시설", value: "beauty" },
  { label: "식음료장", value: "beverage" },
  { label: "자전거대여", value: "bicycle" },
  { label: "캠프파이어", value: "campfire" },
  { label: "휘트니스센터", value: "fitness" },
  { label: "노래방", value: "karaoke" },
  { label: "공용샤워실", value: "publicbath" },
  { label: "공용 PC실", value: "publicpc" },
  { label: "사우나실", value: "sauna" },
  { label: "세미나실", value: "seminar" },
  { label: "스포츠시설", value: "sports" },
  { label: "목욕시설", value: "roombathfacility" },
  { label: "욕조", value: "roombath" },
  { label: "홈시어터", value: "roomhometheater" },
  { label: "에어컨", value: "roomaircondition" },
  { label: "TV", value: "roomtv" },
  { label: "PC", value: "roompc" },
  { label: "케이블설치", value: "roomcable" },
  { label: "인터넷", value: "roominternet" },
  { label: "냉장고", value: "roomrefrigerator" },
  { label: "세면도구", value: "roomtoiletries" },
  { label: "소파", value: "roomsofa" },
  { label: "취사용품", value: "roomcook" },
  { label: "테이블", value: "roomtable" },
  { label: "드라이기", value: "roomhairdryer" },
];
