export const AREA_LIST = [
  { areaCode: "1", areaName: "서울" },
  { areaCode: "2", areaName: "인천" },
  { areaCode: "3", areaName: "대전" },
  { areaCode: "31", areaName: "경기도" },
  { areaCode: "32", areaName: "강원특별자치도" },
  { areaCode: "33", areaName: "충청북도" },
  { areaCode: "34", areaName: "충청남도" },
  { areaCode: "35", areaName: "경상북도" },
  { areaCode: "36", areaName: "경상남도" },
  { areaCode: "37", areaName: "전북특별자치도" },
  { areaCode: "38", areaName: "전라남도" },
  { areaCode: "39", areaName: "제주특별자치도" },
  { areaCode: "4", areaName: "대구" },
  { areaCode: "5", areaName: "광주" },
  { areaCode: "6", areaName: "부산" },
  { areaCode: "7", areaName: "울산" },
  { areaCode: "8", areaName: "세종특별자치시" },
];
